### ISSUE TITLE
This package is not working anymore, isn't it?

### ISSUE THREAD

**Issue by vibarco** [dougransom/vix_utils#27]
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 400 None

Best regards

**Comment by dougransom** [comment]
You need to upgrade.  `pip install --upgrade vix_utils`

**Comment by vibarco** [comment]
> 

Many thanks dougransom,

Still with the problem after doing pip install --upgrade vix_utils and doing vixutil -r

```
Rebuilding data files from Quandl and CBOE
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vixcurrent.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vvixtimeseries.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vix9ddailyprices.csv lines_to_discard 3
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vix3mdailyprices.csv lines_to_discard 2
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vix6mdailyprices.csv lines_to_discard 2
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/gvzhistory.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL_History.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL3M_History.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL6M_History.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL12M_History.csv lines_to_discard 1
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:root:
Writing file   vix6mdailyprices.csv
vix6mdailyprices.csv:  <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>ww2.cboe.com | 523: Origin is unreachable</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-CDEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None

DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG:root:Elapsed time 3.0354511000005004 for add_columns_d  (1,)
DEBUG:root:Elapsed time 1.8081062000001111 for add_columns_d  (2,)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG:root:Elapsed time 1.8682104999998046 for add_columns_d  (3,)
DEBUG:root:Elapsed time 1.7496389000007184 for add_columns_d  (4,)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc

Rebuilding data files from Quandl and CBOE
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vixcurrent.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vvixtimeseries.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vix9ddailyprices.csv lines_to_discard 3
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vix3mdailyprices.csv lines_to_discard 2
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/vix6mdailyprices.csv lines_to_discard 2
DEBUG:root:
Reading URL https://ww2.cboe.com/publish/scheduledtask/mktdata/datahouse/gvzhistory.csv lines_to_discard 1      
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL_History.csv lines_to_discard 1   
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL3M_History.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL6M_History.csv lines_to_discard 1
DEBUG:root:
Reading URL https://ww2.cboe.com//publish/scheduledtask/mktdata/datahouse/RVOL12M_History.csv lines_to_discard 1
DEBUG:root:
Writing file   vix3mdailyprices.csv 
vix3mdailyprices.csv:  <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]--> 
<head>


<title>ww2.cboe.com | 523: Origin is unreachable</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />     
<meta http-equiv="X-UA-C
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG:root:Elapsed time 2.7765565999998216 for add_columns_d  (1,)
DEBUG:root:Elapsed time 1.9307438999994702 for add_columns_d  (2,)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG:root:Elapsed time 2.0237631999998484 for add_columns_d  (3,)
DEBUG:root:Elapsed time 1.856482700000015 for add_columns_d  (4,)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:urllib3.util.retry:Incremented Retry for (url='/api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG:root:Elapsed time 1.91263489999983 for add_columns_d  (5,)
DEBUG:root:Elapsed time 1.9090821999998298 for add_columns_d  (6,)
DEBUG:root:Elapsed time 1.8580203000001347 for add_columns_d  (7,)
DEBUG:root:Elapsed time 2.017404700000043 for add_columns_d  (8,)
DEBUG:urllib3.connectionpool:Retry: /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc
DEBUG:urllib3.connectionpool:https://data.nasdaq.com:443 "GET /api/v3/datasets/CHRIS/CBOE_VX1/data?order=asc HTTP/1.1" 429 None
DEBUG:root:Elapsed time 2.0083371000000625 for add_columns_d  (9,)
DEBUG:root:Elapsed time 18.314133299999412 for concat  (<generator object vix_futures_trade_dates_and_settlement_dates.<locals>.<genexpr> at 0x000001D35315
DEBUG:root:Elapsed time 0.08120270000017626 for pivot_on_contract_maturity  (            Contract Month Settlement Date        tds  Trade Days to Settlement  Days to Settlement
DEBUG:root:Elapsed time 18.417575299999953 for vix_futures_trade_dates_and_settlement_dates  ()
Traceback (most recent call last):
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\Scripts\vixutil.exe\__main__.py", line 4, in <module>
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\vix_utils\vixutil.py", line 264, in <module>
    main()
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\vix_utils\vixutil.py", line 238, in main
    timeit(logging.INFO)(asyncio.run)(vutils.rebuild())
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\vix_utils\futures_utils.py", line 21, in timed
    result = method(*args, **kw)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\vix_utils\vixutil.py", line 78, in rebuild
    (cash_vix, _, wide_vix_calendar) = await asyncio.gather(ch, download_quandl_coro, wide_vix_calendar_coro)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\vix_utils\vix_cash_term_structure.py", line 148, in get_vix_index_histories
    frames_unfixed = await asyncio.gather(*frames_coro)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\vix_utils\vix_cash_term_structure.py", line 143, in read_csv_from_web
    frame = pd.read_csv(input_stream, header=lines_to_discard)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\pandas\io\parsers\readers.py", line 583, in _read
    return parser.read(nrows)
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\pandas\io\parsers\readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "C:\Users\vicente\miniconda3\envs\backtesting-dash\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas\_libs\parsers.pyx", line 812, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas\_libs\parsers.pyx", line 873, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 848, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 859, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas\_libs\parsers.pyx", line 2025, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 13, saw 2
```
Best regards

**Comment by vibarco** [comment]
Hello dougrounsom,

the problem was on my side. The token that i used was not right.

Many thanks for the support.

Best
